apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: jaeger
  name: jaeger
spec:
  ports:
    - name: "jaeger-http"
      port: 16686
      targetPort: 16686
    - name: "jaeger-udp"
      port: 14250
      targetPort: 14250
  selector:
    io.kompose.service: jaeger
status:
  loadBalancer: {}
